FROM oven/bun:1-alpine AS builder
WORKDIR /app

COPY . .

RUN bun install
RUN bun run build:web

# -----------------------------
# Production image
# -----------------------------
FROM oven/bun:1-alpine
WORKDIR /app

# Copia node_modules já resolvido
COPY --from=builder /app/node_modules ./node_modules

# Copia somente o necessário
COPY --from=builder /app/apps/api ./apps/api
COPY --from=builder /app/apps/web/dist ./apps/web/dist
COPY --from=builder /app/packages ./packages
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/bun.lock ./bun.lock
COPY --from=builder /app/tsconfig.base.json ./tsconfig.base.json

ENV NODE_ENV=production
ENV APP_URL=http://localhost:4000
ENV FRONTEND_URL=http://localhost:4000
EXPOSE 4000

CMD ["bun", "--config=/app/apps/api/tsconfig.json", "run", "--cwd", "apps/api", "start"]
